### ISSUE TITLE
运行eval.py程序报错

### ISSUE THREAD

**Issue by amazing5555** [yeyupiaoling/SpeechEmotionRecognition-PaddlePaddle#2]
for x_val, y_val in zip(x.flatten(), y.flatten()):
        c = cm[y_val][x_val] / (np.sum(cm[:, x_val]) + 1e-6)
        # 忽略值太小的
        if c < 1e-4:continue
        plt.text(x_val, y_val, "%0.2f" % (c,), color='red', fontsize=15, va='center', ha='center')
报错内容
Traceback (most recent call last):
  File "D:\SpeechEmotionRecognition-Pytorch-master\SpeechEmotionRecognition-Pytorch-master\eval.py", line 71, in <module>
    evaluate()
  File "D:\SpeechEmotionRecognition-Pytorch-master\SpeechEmotionRecognition-Pytorch-master\eval.py", line 66, in evaluate
    plot_confusion_matrix(cm=cm, save_path='output/log/混淆矩阵_eval.png', class_labels=class_labels, show=False)
  File "D:\SpeechEmotionRecognition-Pytorch-master\SpeechEmotionRecognition-Pytorch-master\utils\utility.py", line 31, in plot_confusion_matrix
    c = cm[y_val][x_val] / (np.sum(cm[:, x_val]) + 1e-6)
IndexError: index 5 is out of bounds for axis 0 with size 5

**Comment by yeyupiaoling** [comment]
可能是没有好的训练结果导致的，你可以注释下面这行代码忽略掉。
```
plot_confusion_matrix(cm=cm, save_path='output/log/混淆矩阵_eval.png',
```

**Comment by amazing5555** [comment]
好的，谢谢
